### ISSUE TITLE
mysql decimal数据类型不支持

### ISSUE THREAD

**Issue by lixqmeiyibao** [long2ice/synch#11]
使用consume时出错，提示  
File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 100, in write_column
    column.write_data(items, buf)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 80, in _write_data
    prepared = self.prepare_items(items)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 61, in prepare_items
    check_item_type(x)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 37, in check_item_type
    raise exceptions.ColumnTypeMismatchException(value)
clickhouse_driver.columns.exceptions.ColumnTypeMismatchException: 0.00

During handling of the above exception, another exception occurred:

**Comment by long2ice** [comment]
decimal是支持的，看一下consumer的log

**Comment by lixqmeiyibao** [comment]
我是用pip直接安装的。
   0e68dd1eb5a740fba71f6ddf085285b7', 'showroom_one_qudao_code': '', 'showroom_one_qudao_name': '', 'showroom_two_qudao_code': '', 'showroom_two_qudao_name': '', 'belonger_name': '阮淑瑜', 'belonger_type': 3, 'belonger_team_uuid': 'ae24167f395c4062880b79c798b7d012', 'belonger_team_name': '超越队', 'belonger_group_uuid': '4e39fcace949457eb55bacc031bbc2e0', 'belonger_group_name': '超越队', 'data_flag': 0}, {'uuid': '8d87df6554ef4dbfb80776c038de0e8c', 'pro_uuid': 'P0552', 'cus_uuid': '', 'one_qudao_code': 'K-0021', 'one_qudao_name': '渠道自拓', 'two_qudao_code': 'K-7754', 'two_qudao_name': '外拓', 'name': '沈先生', 'sex': 0, 'phone': '089034', 'see_time': 0, 'remark': '', 'remark_time': 0, 'source': 1, 'acc_uuid': 'HX4', 'acc_name': '洪霞', 'acc_type': 3, 'acc_team_uuid': '4be5d17297ab4aada569f2bb289f55f5', 'acc_team_name': '玉兰耿先平组', 'acc_group_uuid': '8675c8e93301495ca214f85961a5a985', 'acc_group_name': '耿升平组', 'baobei_yuqi_time': 1593273599, 'vist_yuqi_time': 0, 'trans_yuqi_time': 0, 'trans_time': 0, 'first_vist_time': 0, 'last_vist_time': 0, 'trans_no': '', 'baobei_state': 1, 'fail_reasons': '报备成功', 'cus_state': 0, 'is_valid': 1, 'invalid_type': 0, 'invalid_reasons': '', 'invalid_time': 0, 'team_uuid': '', 'group_uuid': '', 'sales_acc_uuid': '', 'alloc_state': 0, 'create_time': 1592928195, 'edit_time': 1592928195, 'alloc_date': 0, 'state': 1, 'is_del': 0, 'id_no': '', 'phone1': '', 'phone2': '', 'build_type': 0, 'is_hidden': 0, 'is_special': 0, 'special_uuid': '', 'special_name': '', 'special_phone': '', 'special_pro_uuid': '', 'special_type': 0, 'jie_ke_minute': 30, 'house_type': '', 'first_dial_date': 0, 'invalid_repeat_trans': 0, 'risk_tips_content': '', 'trade_type': 2, 'mult_trans_days': 3, 'first_referrer_date': 0, 'acc_phone': '18918396115', 'task_uuid': '', 'restart_days': 999, 'should_commission': Decimal('0.00'), 'reality_commission': Decimal('0.00'), 'commission_handle_time': 0, 'belonger_uuid': 'HX4', 'showroom_one_qudao_code': '', 'showroom_one_qudao_name': '', 'showroom_two_qudao_code': '', 'showroom_two_qudao_name': '', 'belonger_name': '洪霞', 'belonger_type': 3, 'belonger_team_uuid': '4be5d17297ab4aada569f2bb289f55f5', 'belonger_team_name': '平组', 'belonger_group_uuid': '8675c8e93301495ca214f85961a5a985', 'belonger_group_name': '平组', 'data_flag': 0}]
Traceback (most recent call last):
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 100, in write_column
    column.write_data(items, buf)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 80, in _write_data
    prepared = self.prepare_items(items)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 61, in prepare_items
    check_item_type(x)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 37, in check_item_type
    raise exceptions.ColumnTypeMismatchException(value)
clickhouse_driver.columns.exceptions.ColumnTypeMismatchException: 0.00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysql2ch/venv/bin/mysql2ch", line 8, in <module>
    sys.exit(cli())
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/mysql2ch/cli.py", line 93, in cli
    parse_args.run(parse_args)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/mysql2ch/cli.py", line 46, in run
    args.func(args)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/mysql2ch/consumer.py", line 110, in consume
    writer.insert_event(tmp_data, schema, table, tables_pk.get(table))
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/mysql2ch/writer.py", line 205, in insert_event
    self.execute(sql["insert_sql"], sql["insert_data"], types_check=True)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/mysql2ch/writer.py", line 29, in execute
    return self._client.execute(sql, params=params, *args, **kwargs)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/client.py", line 217, in execute
    columnar=columnar
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/client.py", line 372, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/client.py", line 407, in send_data
    self.connection.send_data(block)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 507, in send_data
    self.block_out.write(block)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 39, in write
    self.fout, types_check=block.types_check)
  File "/home/mysql2ch/venv/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 106, in write_column
    column_spec, type(e.args[0]), e.args[0], column_name
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Expected String got <class 'decimal.Decimal'>: 0.00 for column "should_commission".
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by long2ice** [comment]
你的clickhouse should_commission字段类型为string

**Comment by lixqmeiyibao** [comment]
解决了，谢谢。    运行过程中还有这个错误，是什么意思，帮忙看一下
2020-06-24 16:04:54 - mysql2ch.writer:28 - DEBUG - select count(*) as mutation_faild ,concat(database,'.',table)as db,create_time from system.mutations where is_done=0 and database = 'sunac_anchang' group by db,create_time
2020-06-24 16:04:54 - mysql2ch.writer:141 - ERROR - mutations error failed num 3607. delete error please check: [
    {
        "mutation_failed": 11,
        "table": "sunac_anchang.cus_bao_bei_list",
        "create_time": {
            "val": "2020-06-24 16:04:36",
            "_spec_type": "datetime"
        }
    },
    {
        "mutation_failed": 16,
        "table": "sunac_anchang.cus_bao_bei_list",
        "create_time": {
            "val": "2020-06-24 16:03:14",
            "_spec_type": "datetime"
        }
    },
    {
        "mutation_failed": 14,
        "table": "sunac_anchang.cus_bao_bei_list",
        "create_time": {
            "val": "2020-06-24 16:03:51",
            "_spec_type": "datetime"
        }
    },

**Comment by long2ice** [comment]
这是clickhouse后台执行突变，你把insert_num 和insert_interval参数调大一点

**Comment by lixqmeiyibao** [comment]
ok了，谢谢。 如果要同步mysql一个db里面的所有表，可以用通配符吗。

**Comment by long2ice** [comment]
这个现在还不支持

**Comment by lixqmeiyibao** [comment]
谢谢。刚开始接触clickhouse，请多多指教

**Comment by long2ice** [comment]
嗯，你可以加QQ群交流
