### ISSUE TITLE
没有kafka模块

### ISSUE THREAD

**Issue by rechardwang** [long2ice/synch#15]
使用docker-compose部署时，synch镜像没有kafka模块

**Comment by long2ice** [comment]
master分支的镜像有点问题，用dev分支镜像就可以了

**Comment by rechardwang** [comment]
dev分支里面的docker-compose也是用的long2ice/synch镜像啊

**Comment by long2ice** [comment]
改一下tag，long2ice/synch:dev

**Comment by rechardwang** [comment]
```
consumer.test_1  | Traceback (most recent call last):
consumer.test_1  |   File "/usr/local/bin/synch", line 11, in <module>
consumer.test_1  |     load_entry_point('synch', 'console_scripts', 'synch')()
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
consumer.test_1  |     return self.main(*args, **kwargs)
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
consumer.test_1  |     rv = self.invoke(ctx)
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
consumer.test_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
consumer.test_1  |     return ctx.invoke(self.callback, **ctx.params)
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
consumer.test_1  |     return callback(*args, **kwargs)
consumer.test_1  |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
consumer.test_1  |     return f(get_current_context(), *args, **kwargs)
consumer.test_1  |   File "/synch/synch/cli.py", line 73, in consume
consumer.test_1  |     tables = Settings.get_source_db_database_tables_name(alias, schema)
consumer.test_1  |   File "/synch/synch/settings.py", line 42, in get_source_db_database_tables_name
consumer.test_1  |     map(lambda x: x.get("table"), cls.get_source_db_database_tables(alias, database))
consumer.test_1  |   File "/synch/synch/settings.py", line 51, in get_source_db_database_tables
consumer.test_1  |     source_db_database = cls.get_source_db_database(alias, database)
consumer.test_1  |   File "/synch/synch/settings.py", line 36, in get_source_db_database
consumer.test_1  |     return next(filter(lambda x: x.get("database") == database, source_db.get("databases")))
```

**Comment by rechardwang** [comment]
docker-compose里面消费者跑不成功，但是我直接用synch --alias mysql_db consume --schema database  这命令直接用容器跑是没问题

**Comment by rechardwang** [comment]
直接docker exec 进入容器 执行 synch --alias mysql_db consume --schema 试了可以同步一条数据，为什么呢？

**Comment by long2ice** [comment]
docker-compose logs看一下日志

**Comment by rechardwang** [comment]
消费者一直就是报上面我发的错误

**Comment by long2ice** [comment]
配置文件配置的与docker-compose命令不匹配

**Comment by rechardwang** [comment]
好的，我在仔细看看，那么在数据库方面我需要创建一个用来同步的用户，除了可以给GRANT Replication Client, Replication Slave, Super 这些权限以外 还需要补充吗？

**Comment by long2ice** [comment]
差不多就这些
