### ISSUE TITLE
是否支持建表DDL的实时同步？

### ISSUE THREAD

**Issue by peerhyw** [long2ice/synch#34]
尝试了一下在mysql新建表，clickhouse这边监听的时候不会同步建表

**Comment by long2ice** [comment]
不会，需要更改配置文件

**Comment by peerhyw** [comment]
> 不会，需要更改配置文件

请问更改配置文件的格式是怎么样的，我看synch.yaml这个文件不知道如何添加这个配置，添加完是否也支持alter table这些ddl语句？

**Comment by peerhyw** [comment]
> 不会，需要更改配置文件

你好，我看readme里是支持 DML 同步与 DDL 同步， 支持增加字段、删除字段、更改字段的，但是我测试的时候在mysql里修改字段名称，clickhouse里没有同步更改，不知道是否要修改哪里的配置，麻烦了

**Comment by long2ice** [comment]
查看日志看有没有报错

**Comment by peerhyw** [comment]
> 查看日志看有没有报错

2020-10-23 10:13:02 - synch.reader.mysql:126 - DEBUG - send to queue success: key:,event:{'table': '`clickhouse``qitw0_users`', 'schema': '', 'action': 'query', 'values': {'query': 'alter table .`clickhouse``qitw0_users` rename column `otepp` to `otep`'}, 'event_unixtime': 1603419182485626, 'action_seq': 0}
2020-10-23 10:13:02 - synch.reader.mysql:127 - DEBUG - success set binlog pos:mysql-bin.000026:2600
2020-10-23 10:13:02 - synch.reader:83 - INFO - success send 2 events for .None
2020-10-23 10:13:02 - synch.replication.clickhouse:54 - DEBUG - INSERT INTO synch.log (alias, schema, table, num, type, created_at) VALUES ('mysql_db', '', 'None', 2, 1, '2020-10-23 10:13:02')

你好，我在produce里面终端看到的信息就是这样，不知道具体的报错内容在哪里能看到，consume一直是insert current 0 events

**Comment by long2ice** [comment]
启动的命令要指定消费哪个库的数据

**Comment by peerhyw** [comment]
> 启动的命令要指定消费哪个库的数据

有指定的，我生产和消费的命令分别是这样的

synch --alias mysql_db produce
synch --alias mysql_db consume --schema clickhouse

插入，更新和删除的时候是正常同步的

我在mysql执行修改字段名称的时候报这个错误
2020-10-23 10:40:05 - synch.convert:110 - WARNING - Parse query error, query: alter table \`clickhouse\`.\`qitw0_users\`  change column \`otep\` \`otepp\` varchar(1000) character set 'utf8mb4' collate 'utf8mb4_unicode_ci' not null default '' comment 'one time emergency passwords', err: string index out of range
Traceback (most recent call last):
  File "/home/peer/.local/lib/python3.8/site-packages/synch/convert.py", line 108, in to_clickhouse
    ret = cls.get_parse_ret(query)
  File "/home/peer/.local/lib/python3.8/site-packages/synch/convert.py", line 53, in get_parse_ret
    statement = parsed.statements[0]  # type:ast.stmt
IndexError: string index out of range
Stack (most recent call last):
  File "/home/peer/.local/bin/synch", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/peer/.local/lib/python3.8/site-packages/synch/cli.py", line 93, in produce
    reader.start_sync(broker)
  File "/home/peer/.local/lib/python3.8/site-packages/synch/reader/mysql.py", line 111, in start_sync
    for schema, table, event, file, pos in self._binlog_reading(
  File "/home/peer/.local/lib/python3.8/site-packages/synch/reader/mysql.py", line 162, in _binlog_reading
    table, convent_sql = SqlConvert.to_clickhouse(
  File "/home/peer/.local/lib/python3.8/site-packages/synch/convert.py", line 110, in to_clickhouse
    logger.warning(

**Comment by long2ice** [comment]
貌似alter语句转换失败，DDL仅支持有限的同步，你可以使用`synch etl ...  --renew`自动重新全量导入并同步最新表结构

**Comment by peerhyw** [comment]
> 貌似alter语句转换失败，DDL仅支持有限的同步，你可以使用`synch etl ... --renew`自动重新全量导入并同步最新表结构

嗯 看了下应该是mysqlparse这个库的解析支持不全 用自动全量的话数据量大的话应该也不合适吧 感觉只能尽可能保持结构不变或者手动改变了
