### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'synch.yaml'

### ISSUE THREAD

**Issue by cqupgj** [long2ice/synch#35]
运行：
synch --alias mysql_db etl --renew
报错信息：
Traceback (most recent call last):
  File "f:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Python38\Scripts\synch.exe\__main__.py", line 7, in <module>
  File "f:\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "f:\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "f:\python38\lib\site-packages\click\core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "f:\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "f:\python38\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\python38\lib\site-packages\synch\cli.py", line 36, in cli
    init(config)
  File "f:\python38\lib\site-packages\synch\factory.py", line 159, in init
    Settings.init(config_file)
  File "f:\python38\lib\site-packages\synch\settings.py", line 12, in init
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './synch.yaml'

**Comment by long2ice** [comment]
需要制定配置文件目录，默认为当前路径

**Comment by cqupgj** [comment]
你好我第一次接触python项目，怎么制定配置文件目录呢？可以给个列子吗。

**Comment by long2ice** [comment]
指定配置文件，synch -h查看帮助

**Comment by cqupgj** [comment]
嗯，多谢！

**Comment by cqupgj** [comment]
>synch --alias mysql_db etl --schema test2-ppy-op  --renew

2020-11-04 11:01:32 - synch.replication.clickhouse:54 - DEBUG - create database if not exists synch
2020-11-04 11:01:32 - synch.replication.clickhouse:54 - DEBUG - create table if not exists synch.log
(
    id         int,
    alias      String,
    schema     String,
    table      String,
    num        int,
    type       int,
    created_at DateTime
)
    engine = ReplacingMergeTree partition by toYYYYMM(created_at) order by id;
2020-11-04 11:01:32 - synch.reader:35 - DEBUG - select COLUMN_NAME from information_schema.COLUMNS where TABLE_SCHEMA='test2-ppy-op' and TABLE_NAME='auth_api' and COLUMN_KEY='PRI'
2020-11-04 11:01:32 - synch.replication.clickhouse:54 - DEBUG - select 1 from system.databases where name = 'test2-ppy-op'
2020-11-04 11:01:32 - synch.replication.clickhouse:54 - DEBUG - create database if not exists test2-ppy-op
Traceback (most recent call last):
  File "f:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Python38\Scripts\synch.exe\__main__.py", line 7, in <module>
  File "f:\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "f:\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "f:\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "f:\python38\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\python38\lib\site-packages\synch\cli.py", line 57, in etl
    etl_full(alias, schema, tables_pk, renew)
  File "f:\python38\lib\site-packages\synch\replication\etl.py", line 22, in etl_full
    writer.create_database(schema, Settings.cluster_name())
  File "f:\python38\lib\site-packages\synch\writer\__init__.py", line 48, in create_database
    return self.execute(sql)
  File "f:\python38\lib\site-packages\synch\writer\__init__.py", line 55, in execute
    return self._client.execute(sql, params=params, *args, **kwargs)
  File "f:\python38\lib\site-packages\clickhouse_driver\client.py", line 220, in execute
    rv = self.process_ordinary_query(
  File "f:\python38\lib\site-packages\clickhouse_driver\client.py", line 346, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "f:\python38\lib\site-packages\clickhouse_driver\client.py", line 89, in receive_result
    return result.get_result()
  File "f:\python38\lib\site-packages\clickhouse_driver\result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "f:\python38\lib\site-packages\clickhouse_driver\client.py", line 101, in packet_generator
    packet = self.receive_packet()
  File "f:\python38\lib\site-packages\clickhouse_driver\client.py", line 118, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
**DB::Exception: Syntax error: failed at position 36 ('-'): -ppy-op. Expected one of: storage definition, ENGINE, UUID, INTO OUTFILE, SETTINGS, ON, FORMAT. Stack trace:**

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e2f1a0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe73a32d in /usr/bin/clickhouse
2. ? @ 0x16a557eb in /usr/bin/clickhouse
3. ? @ 0x15e3e53e in /usr/bin/clickhouse
4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15e40682 in /usr/bin/clickhouse
5. DB::TCPHandler::runImpl() @ 0x164ee4a5 in /usr/bin/clickhouse
6. DB::TCPHandler::run() @ 0x164ef210 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x18d4d00b in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x18d4d49b in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x18ecbf76 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x18ec7370 in /usr/bin/clickhouse
11. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

看起来数据库名不能包含减号(-)，我的CH版本是v20.9.4.76-stable。这个问题我用Tabix时也发现过，不过在命令行中用clickhouse-client创建名字带有减号的数据库没这个问题。

**Comment by long2ice** [comment]
可以试试手动建库或者升级版本
