### ISSUE TITLE
docker运行mysql2ch-struct.error: 'I' format requires 0 <= number <= 4294967295

### ISSUE THREAD

**Issue by marx-zhang** [long2ice/synch#40]
功能正常可用，运行时报错

Traceback (most recent call last):
  File "/synch/synch/replication/continuous.py", line 126, in continuous_etl
    writer.insert_events(schema, table, insert_events)
  File "/synch/synch/writer/__init__.py", line 82, in insert_events
    self.execute(insert_sql, list(map(lambda x: x.get("values"), insert_data)))
  File "/synch/synch/writer/__init__.py", line 55, in execute
    return self._client.execute(sql, params=params, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 214, in execute
    rv = self.process_insert_query(
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 371, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 407, in send_data
    self.connection.send_data(block)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 509, in send_data
    self.block_out.write(block)
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 112, in write_column
    raise errors.TypeMismatchError(
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Repeat query with types_check=True for detailed info. Column PUBLISH_DATE: 'I' format requires 0 <= number <= 4294967295
字段“PUBLISH_DATE”是datatime类型，大部分数据同步成功，应该是有个别数据报错了
请教：这是什么原因的报错？

**Comment by long2ice** [comment]
看报错是clickhouse的字段类型不匹配

**Comment by marx-zhang** [comment]
个别脏数据导致时间超出了clickhouse 支持的时间范围
