### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by zhechu** [long2ice/synch#49]
CentOS7 执行 pip install synch 异常（已安装 python 3.7 和 pip3）
```shell
WARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.1.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 299 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/python3/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lyq28ain
         cwd: /tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/
    Complete output (10 lines):
    /bin/sh: mysql_config: 未找到命令
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-c31l6e8r/mysqlclient_7f635c4393eb4ce88ef9a713c1ffb032/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.0.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 336 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/python3/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7v_13f8p
         cwd: /tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/
    Complete output (10 lines):
    /bin/sh: mysql_config: 未找到命令
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-c31l6e8r/mysqlclient_8f4f36bd64564c3095482e0cb4995727/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting synch
  Downloading synch-0.6.7-py3-none-any.whl (38 kB)
Collecting sqlparse
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 392 kB/s 
Collecting synch
  Downloading synch-0.6.6-py3-none-any.whl (37 kB)
  Downloading synch-0.6.1-py3-none-any.whl (36 kB)
Collecting pydantic
  Downloading pydantic-1.8.2-cp37-cp37m-manylinux2014_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 740 kB/s 
Collecting synch
  Downloading synch-0.6.0-py3-none-any.whl (35 kB)
ERROR: Cannot install synch==0.6.0, synch==0.6.1, synch==0.6.6, synch==0.6.7 and synch==0.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    synch 0.7.1 depends on mysqlclient
    synch 0.6.7 depends on mysqlclient
    synch 0.6.6 depends on mysqlclient
    synch 0.6.1 depends on mysqlclient
    synch 0.6.0 depends on mysqlclient

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Comment by long2ice** [comment]
安装mysql-devel

**Comment by zhechu** [comment]
python 依赖太复杂了，还是用了 docker 部署
