### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ewsq** [long2ice/synch#56]
Centos 7.3  ClickHouse 21.3.5.42  最新的synch 报如下错误，不知是什么原因？

[root@webserver synch]# synch --alias mysql_db etl --schema fmmp --tables T_AGENCY
Traceback (most recent call last):
  File "/usr/local/python/bin/synch", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/python/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/python/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    super().invoke(ctx)
  File "/usr/local/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/python/lib/python3.9/site-packages/synch/cli.py", line 36, in cli
    init(config)
  File "/usr/local/python/lib/python3.9/site-packages/synch/factory.py", line 161, in init
    dsn = Settings.get("sentry", "dsn")
  File "/usr/local/python/lib/python3.9/site-packages/synch/settings.py", line 105, in get
    c = c.get(arg)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by long2ice** [comment]
试试从源码安装
