### ISSUE TITLE
UnicodeDecodeError -  'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by itziklavon** [long2ice/synch#57]
Hi, i'm getting the fillowing error from the producer(using docker compose, with dev tag, as sentry breaks latest tag)
what might cause it?
i see producer is connected, and pulling data + sending to queue
some records have this error, is there a way to overcome it?

```
producer_1  | Traceback (most recent call last):
producer_1  |   File "/usr/local/bin/synch", line 5, in <module>
producer_1  |     cli()
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
producer_1  |     return self.main(*args, **kwargs)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
producer_1  |     rv = self.invoke(ctx)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
producer_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
producer_1  |     return ctx.invoke(self.callback, **ctx.params)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
producer_1  |     return __callback(*args, **kwargs)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
producer_1  |     return f(get_current_context(), *args, **kwargs)
producer_1  |   File "/synch/synch/cli.py", line 91, in produce
producer_1  |     reader.start_sync(broker)
producer_1  |   File "/synch/synch/reader/mysql.py", line 109, in start_sync
producer_1  |     for schema, table, event, file, pos in self._binlog_reading(
producer_1  |   File "/synch/synch/reader/mysql.py", line 178, in _binlog_reading
producer_1  |     for row in binlog_event.rows:
producer_1  |   File "/usr/local/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 433, in rows
producer_1  |     self._fetch_rows()
producer_1  |   File "/usr/local/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 428, in _fetch_rows
producer_1  |     self.__rows.append(self._fetch_one_row())
producer_1  |   File "/usr/local/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 481, in _fetch_one_row
producer_1  |     row["values"] = self._read_column_data(self.columns_present_bitmap)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 132, in _read_column_data
producer_1  |     values[name] = self.__read_string(1, column)
producer_1  |   File "/usr/local/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 224, in __read_string
producer_1  |     string = string.decode(encoding)
producer_1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by long2ice** [comment]
Looks like bug of pymysqlreplication
