### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ndj888** [long2ice/synch#59]
Traceback (most recent call last):
  File "/usr/local/bin/synch", line 5, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/synch/synch/cli.py", line 79, in consume
    continuous_etl(
  File "/synch/synch/replication/continuous.py", line 135, in continuous_etl
    writer.insert_events(schema, table, insert_events)
  File "/synch/synch/writer/__init__.py", line 80, in insert_events
    self.execute(insert_sql, list(map(lambda x: x.get("values"), insert_data)))
  File "/synch/synch/writer/__init__.py", line 53, in execute
    return self._client.execute(sql, params=params, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 242, in execute
    rv = self.process_insert_query(
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 471, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 524, in send_data
    self.connection.send_data(block)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 554, in send_data
    self.block_out.write(block)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/columns/service.py", line 107, in write_column
    column.write_data(items, buf)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 80, in _write_data
    prepared = self.prepare_items(items)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 69, in prepare_items
    self.before_write_items(items, nulls_map=nulls_map)
  File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/columns/datetimecolumn.py", line 94, in before_write_items
    if item.tzinfo is not None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'

**Comment by ndj888** [comment]
mysql datetime 类型 这种 无效的默认值，不能同步到clickhouse ，需要更正
DEFAULT '0000-00-00 00:00:00'
